### ISSUE TITLE
DGIndexNV Command Syntax is wrong

### ISSUE THREAD

**Issue by Cwavs** [Irrational-Encoding-Wizardry/vs-parsedvd#19]
The command that the DGIndexNV indexer will generate is using the wrong syntax causing DGIndexNV to fail for ambiguous reasons, the command syntax the get_cmd function creates is:
`{path/to/dgindex} -i "{path/to/vobfile1},{path/to/vobfile2}" -o {path/to/output} -h`
it should actually be:
`{path/to/dgindex -i "{path/to/vobfile1}","{path/tovobfile2}" -o {path/to/output} -h`
It looks like the current syntax causes DGIndex to treat all the file names as one file, which causes it to silently crash.

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-parsedvd/commit/1c0ec7599001352b84958d9a4e8d361b78b348aa
